Repository 202212-GIZ-YE-FEW/iDev, pull requests merged in 2023-04, with the labels that each got.

#70 Feature/enhance team page no ref
  public/locales/ar/common.json
  public/locales/ar/team.json
  public/locales/en/common.json
  public/locales/en/team.json
  public/team/AbdulmajeedJaafer.png
  public/team/AhmedMohammed.png
  public/team/AllanSaleh.png
  public/team/AvrazZebary.png
  public/team/PayamAbubakr.png
  public/team/SnoorMadih.png
  src/components/TeamMember.jsx
  src/components/__test__/__snapshots__/TeamMember.test.js.snap
  src/pages/_app.jsx
  src/pages/index.jsx
  src/pages/team.jsx
Labels: enhancement

#104 refactor: adding head and translation for thanks page
  public/locales/en/common.json
  src/pages/thanks.jsx
Labels: enhancement

#95 Feature/design therapist create page 23
  public/locales/ar/signup.json
  public/locales/en/signup.json
  src/components/FormTitle.jsx
  src/components/PageIntro.jsx
  src/components/__test__/__snapshots__/CommunicateThroughSection.test.js.snap
  src/components/__test__/__snapshots__/RecentBlogSection.test.js.snap
  src/components/__test__/__snapshots__/TicketSection.test.js.snap
  src/components/__test__/__snapshots__/TrustTherapistSection.test.js.snap
  src/components/ui/Input.jsx
  src/components/ui/__test__/Therapist.test.js
  src/components/ui/__test__/__snapshots__/Singup.test.js.snap
  src/components/ui/__test__/__snapshots__/Therapist.test.js.snap
  src/pages/index.jsx
  src/pages/login.jsx
  src/pages/signup.jsx
  src/pages/therapist.jsx
Labels: changes-requested

#105 refactor: enhance login page
  src/components/ui/__test__/__snapshots__/Login.test.js.snap
  src/components/ui/__test__/__snapshots__/Therapist.test.js.snap
  src/pages/login.jsx
  src/pages/signup.jsx
  src/pages/therapist.jsx
Labels: enhancement

#107 feat: add book appointment page
  .github/workflows/lint.yml
  public/locales/ar/appointment.json
  public/locales/en/appointment.json
  src/components/AppointmentCallout.jsx
  src/components/AuthSocialMedia.jsx
  src/components/BookAppointment.jsx
  src/components/HeroSection.jsx
  src/components/PageIntro.jsx
  src/components/Stepper.jsx
  src/components/TicketSection.jsx
  src/components/TrustTherapistSection.jsx
  src/components/__test__/BookAppointment.text.js
  src/components/__test__/__snapshots__/CommunicateThroughSection.test.js.snap
  src/components/__test__/__snapshots__/HeroSection.test.js.snap
  src/components/__test__/__snapshots__/RecentBlogSection.test.js.snap
  src/components/__test__/__snapshots__/TicketSection.test.js.snap
  src/components/__test__/__snapshots__/TrustTherapistSection.test.js.snap
  src/components/ui/__test__/__snapshots__/Therapist.test.js.snap
  src/components/ui/radiogroup/RadioGroup.jsx
  src/components/ui/radiogroup/RadioGroup.test.js
  src/components/ui/radiogroup/RadioInputItem.jsx
  src/components/ui/radiogroup/__snapshots__/RadioGroup.test.js.snap
  src/components/ui/radiogroup/__snapshots__/RadioInputItem.test.js.snap
  src/components/ui/textarea/Textarea.jsx
  src/components/ui/textarea/__snapshots__/Textarea.test.js.snap
  src/pages/404.jsx
  src/pages/_document.jsx
  src/pages/api/hello.js
  src/pages/appointment.jsx
  src/pages/signup.jsx
Labels: UI/UX, feature

#109 Feature/design requirements page 80
  .env
  public/locales/ar/requirements.json
  public/locales/en/requirements.json
  public/requirements.svg
  src/components/Navbar.jsx
  src/components/Requirement.jsx
  src/components/RequirementsSection.jsx
  src/components/__test__/Requirement.test.js
  src/components/__test__/RequirementsSection.test.js
  src/components/__test__/__snapshots__/Requirement.test.js.snap
  src/components/__test__/__snapshots__/RequirementsSection.test.js.snap
  src/firebase-config/firebase.js
  src/firebase/addData.js
  src/firebase/config.js
  src/firebase/firebaseProvidersMethods.js
  src/firebase/getData.js
  src/pages/login.jsx
  src/pages/requirements.jsx
  src/pages/signup.jsx
Labels: UI/UX, feature

#113 docs: firebase structure for contact us functionality
  firebase_structure/contact_type_ar.png
  firebase_structure/contact_type_en.png
  firebase_structure/visitors_messages.png
  src/firebase/structures/visitors_messages.md
Labels: documentation, add-docs, feature

#118 Feature/design & develop the contact us
  package-lock.json
  package.json
  public/contactus.svg
  public/edit_profile_icon.png
  public/locales/ar/common.json
  public/locales/ar/contact_us.json
  public/locales/ar/validation.json
  public/locales/en/contact_us.json
  public/locales/en/validation.json
  public/profile-icon.png
  src/components/Footer.jsx
  src/components/Navbar.jsx
  src/components/__test__/__snapshots__/Footer.test.js.snap
  src/components/ui/Input.jsx
  src/components/ui/__test__/__snapshots__/Input.test.js.snap
  src/components/ui/__test__/__snapshots__/Login.test.js.snap
  src/components/ui/__test__/__snapshots__/Singup.test.js.snap
  src/components/ui/__test__/__snapshots__/Therapist.test.js.snap
  src/components/ui/textarea/Textarea.jsx
  src/components/ui/textarea/Textarea.test.js
  src/components/ui/textarea/__snapshots__/Textarea.test.js.snap
  src/firebase/addData.js
  src/pages/contact-us.jsx
  src/utils/constants.jsx
  src/utils/validationSchema.jsx
  tailwind.config.js
Labels: UI/UX, api

#71 33 design profile preview component
  package-lock.json
  public/edit-profile-icon.svg
  public/edit_profile_icon.png
  public/profile-icon.png
  public/profile-icon.svg
  src/components/ui/PreviewProfile.jsx
  src/components/ui/__test__/PreviewProfile.test.jsx
  src/components/ui/__test__/__snapshots__/PreviewProfile.test.jsx.snap
Labels: refactor, UI/UX, changes-requested

#117 Feature/build book appointment firebase functionality 89
  .env
  firebase_structure/appointments.png
  package-lock.json
  package.json
  src/components/AppointmentCallout.jsx
  src/components/BookAppointment.jsx
  src/components/BookAppointment/BringsHere.jsx
  src/components/BookAppointment/CounselingType.jsx
  src/components/BookAppointment/Issues.jsx
  src/components/BookAppointment/RelationshipStatus.jsx
  src/components/BookAppointment/SpecificQualities.jsx
  src/components/BookAppointment/TherapyBefore.jsx
  src/components/BookAppointment/__test__/BringsHere.test.js
  src/components/BookAppointment/__test__/CounselingType.test.js
  src/components/BookAppointment/__test__/Issues.test.js
  src/components/BookAppointment/__test__/RelationshipStatus.test.js
  src/components/BookAppointment/__test__/SpecificQualities.test.js
  src/components/BookAppointment/__test__/TherapyBefore.test.js
  src/components/BookAppointment/__test__/__snapshots__/BringsHere.test.js.snap
  src/components/BookAppointment/__test__/__snapshots__/CounselingType.test.js.snap
  src/components/BookAppointment/__test__/__snapshots__/Issues.test.js.snap
  src/components/BookAppointment/__test__/__snapshots__/RelationshipStatus.test.js.snap
  src/components/BookAppointment/__test__/__snapshots__/SpecificQualities.test.js.snap
  src/components/BookAppointment/__test__/__snapshots__/TherapyBefore.test.js.snap
  src/components/Stepper.jsx
  src/config/nodemailer.js
  src/firebase/structures/visitors_messages.md
  src/pages/api/appointments.js
  src/utils/api.js
Labels: feature, api

#128 chore(release): 0.1.0
  .github/release.yml
  .versionrc
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#120 Feature/enhance the contact us page api functionality 94
  package-lock.json
  package.json
  public/locales/ar/response.json
  public/locales/en/response.json
  src/components/__test__/__snapshots__/AreYouCounselor.test.js.snap
  src/components/__test__/__snapshots__/HeroSection.test.js.snap
  src/components/__test__/__snapshots__/RequirementsSection.test.js.snap
  src/components/__test__/__snapshots__/TicketItem.test.js.snap
  src/components/__test__/__snapshots__/TicketSection.test.js.snap
  src/components/__test__/__snapshots__/TrustTherapistSection.test.js.snap
  src/components/ui/Button.jsx
  src/components/ui/Input.jsx
  src/components/ui/__test__/__snapshots__/Button.test.js.snap
  src/components/ui/__test__/__snapshots__/Login.test.js.snap
  src/components/ui/__test__/__snapshots__/Singup.test.js.snap
  src/components/ui/__test__/__snapshots__/Therapist.test.js.snap
  src/components/ui/textarea/Textarea.jsx
  src/pages/_app.jsx
  src/pages/api/contact.js
  src/pages/contact-us.jsx
  src/template/TransactionalEmail.js
  src/template/assets/contact.svg
  src/template/assets/logo.svg
Labels: enhancement, UI/UX, feature, api

#137 Feature/re organize homepage components 136
  src/components/HomePage.jsx
  src/components/Homepage/AreYouCounselor.jsx
  src/components/Homepage/CommunicateThroughItem.jsx
  src/components/Homepage/CommunicateThroughSection.jsx
  src/components/Homepage/HeroSection.jsx
  src/components/Homepage/RecentBlogItem.jsx
  src/components/Homepage/RecentBlogSection.jsx
  src/components/Homepage/TicketItem.jsx
  src/components/Homepage/TicketSection.jsx
  src/components/Homepage/TrustTherapistSection.jsx
  src/components/Homepage/__test__/AreYouCounselor.test.js
  src/components/Homepage/__test__/CommunicateThroughItem.test.js
  src/components/Homepage/__test__/CommunicateThroughSection.test.js
  src/components/Homepage/__test__/HeroSection.test.js
  src/components/Homepage/__test__/RecentBlogItem.test.js
  src/components/Homepage/__test__/RecentBlogSection.test.js
  src/components/Homepage/__test__/TicketItem.test.js
  src/components/Homepage/__test__/TicketSection.test.js
  src/components/Homepage/__test__/TrustTherapistSection.test.js
  src/components/Homepage/__test__/__snapshots__/AreYouCounselor.test.js.snap
  src/components/Homepage/__test__/__snapshots__/CommunicateThroughItem.test.js.snap
  src/components/Homepage/__test__/__snapshots__/CommunicateThroughSection.test.js.snap
  src/components/Homepage/__test__/__snapshots__/HeroSection.test.js.snap
  src/components/Homepage/__test__/__snapshots__/RecentBlogItem.test.js.snap
  src/components/Homepage/__test__/__snapshots__/RecentBlogSection.test.js.snap
  src/components/Homepage/__test__/__snapshots__/TicketItem.test.js.snap
  src/components/Homepage/__test__/__snapshots__/TicketSection.test.js.snap
  src/components/Homepage/__test__/__snapshots__/TrustTherapistSection.test.js.snap
  src/components/__test__/HomePage.test.js
  src/components/__test__/__snapshots__/HomePage.test.js.snap
  src/pages/index.jsx
Labels: enhancement, changes-requested, info-needed

#129 36 story build the edit profile page
  public/locales/ar/profile.json
  public/locales/en/profile.json
  src/components/ui/Dropdown.jsx
  src/components/ui/Input.jsx
  src/components/ui/PreviewProfile.jsx
  src/components/ui/__test__/__snapshots__/Dropdown.test.js.snap
  src/components/ui/__test__/__snapshots__/Input.test.js.snap
  src/components/ui/__test__/__snapshots__/Login.test.js.snap
  src/components/ui/__test__/__snapshots__/PreviewProfile.test.jsx.snap
  src/components/ui/__test__/__snapshots__/Signup.test.js.snap
  src/pages/editprofile.jsx
Labels: UI/UX

#140 Feature/design the buy ticket page following the mobile first approach 121
  public/images/blue-overlay.png
  public/images/master-card.svg
  public/images/pink-overlay.png
  public/images/visa.svg
  public/images/yellow-overlay.png
  public/locales/ar/payment.json
  public/locales/en/payment.json
  src/components/BookAppointment/CounselingType.jsx
  src/components/BookAppointment/Issues.jsx
  src/components/BookAppointment/RelationshipStatus.jsx
  src/components/BookAppointment/SpecificQualities.jsx
  src/components/BookAppointment/TherapyBefore.jsx
  src/components/BookAppointment/__test__/__snapshots__/CounselingType.test.js.snap
  src/components/BookAppointment/__test__/__snapshots__/Issues.test.js.snap
  src/components/BookAppointment/__test__/__snapshots__/RelationshipStatus.test.js.snap
  src/components/BookAppointment/__test__/__snapshots__/SpecificQualities.test.js.snap
  src/components/BookAppointment/__test__/__snapshots__/TherapyBefore.test.js.snap
  src/components/ui/radiogroup/RadioGroup.jsx
  src/components/ui/radiogroup/RadioGroup.stories.jsx
  src/components/ui/radiogroup/RadioGroup.test.js
  src/components/ui/radiogroup/RadioInputItem.jsx
  src/components/ui/radiogroup/__snapshots__/RadioInputItem.test.js.snap
  src/pages/contact-us.jsx
  src/pages/payment/payment-methods.jsx
  src/pages/therapist.jsx
Labels: needs-detailed-design, UI/UX

#141 Add Blog page and Create Blog page with it's functionality
  next.config.js
  package-lock.json
  package.json
  public/images/upload-image.svg
  public/locales/ar/blog.json
  public/locales/ar/common.json
  public/locales/ar/home.json
  public/locales/en/blog.json
  public/locales/en/common.json
  public/locales/en/home.json
  src/components/BlogItem.jsx
  src/components/BlogsSection.jsx
  src/components/HomePage.jsx
  src/components/Homepage/RecentBlogItem.jsx
  src/components/Homepage/__test__/RecentBlogSection.test.js
  src/components/Homepage/__test__/__snapshots__/RecentBlogItem.test.js.snap
  src/components/Navbar.jsx
  src/components/Subscribe.jsx
  src/components/__test__/BlogItem.test.js
  src/components/__test__/BlogsSection.test.js
  src/components/__test__/__snapshots__/BlogItem.test.js.snap
  src/components/__test__/__snapshots__/BlogsSection.test.js.snap
  src/components/__test__/__snapshots__/Footer.test.js.snap
  src/components/__test__/__snapshots__/HomePage.test.js.snap
  src/components/__test__/__snapshots__/Subscribe.test.js.snap
  src/firebase/addImage.js
  src/firebase/config.js
  src/firebase/getDocById.js
  src/firebase/getImage.js
  src/layout/Layout.jsx
  src/pages/_app.jsx
  src/pages/api/create_blog.js
  src/pages/blogs/[id].jsx
  src/pages/blogs/create.jsx
  src/pages/contact-us.jsx
  src/pages/index.jsx
  src/utils/constants.jsx
Labels: UI/UX, authentication, feature

#150 Fix/fix change locale bug 145
  next-i18next.config.js
  src/components/Navbar.jsx
  src/components/__test__/Navbar.test.js
  src/components/__test__/__snapshots__/Navbar.test.js.snap
  src/layout/Layout.jsx
  src/pages/_document.jsx
Labels: 🪲bug

#162 feat: design responsive chatroom along with locale
  next-i18next.config.js
  public/locales/ar/chatroom.json
  public/locales/en/chatroom.json
  src/pages/_document.jsx
  src/pages/chatroom.jsx
Labels: UI/UX
