Repository 202212-GIZ-YE-FEW/iDev, pull requests merged in 2023-03, with the labels that each got.

#39 Feature/design button component 3
  src/components/ui/Button.jsx
  src/components/ui/__test__/Button.test.js
  src/components/ui/__test__/__snapshots__/Button.test.js.snap
  tailwind.config.js
Labels: enhancement

#38 Feature/update readme file for deployment info 37
  .gitignore
  README.md
Labels: documentation, add-description, add-docs

#41 Feature/design subscribe component 15
  src/components/Subscribe.jsx
  src/components/__test__/Subscribe.test.js
  src/components/__test__/__snapshots__/Subscribe.test.js.snap
  tailwind.config.js
Labels: review-codacy, changes-requested

#45 Feature/design footer 2
  .gitignore
  package-lock.json
  package.json
  src/components/Footer.jsx
  src/components/Subscribe.jsx
  src/components/__test__/Footer.test.js
  src/components/__test__/__snapshots__/Footer.test.js.snap
  src/components/__test__/__snapshots__/Subscribe.test.js.snap
  src/constants.jsx
  src/layout/Layout.jsx
  src/pages/404.jsx
  src/pages/index.jsx
  tailwind.config.js
Labels: enhancement, review-codacy, changes-requested

#48 Feature/design textarea controlform 26
  .eslintrc.js
  .github/workflows/lint.yml
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/components/ui/textarea/Textarea.jsx
  src/components/ui/textarea/Textarea.stories.jsx
  src/components/ui/textarea/Textarea.test.js
  src/components/ui/textarea/__snapshots__/Textarea.test.js.snap
  src/styles/tailwind.css
Labels: UX

#44 Feature/design input formcontrol 25
  src/components/ui/Input.jsx
  src/components/ui/__test__/Input.test.js
  src/components/ui/__test__/__snapshots__/Input.test.js.snap
  tailwind.config.js
Labels: changes-requested

#54 Feature/design form title componen 53
  src/components/ui/FormTitle.jsx
  src/components/ui/__test__/FormTitle.test.js
  src/components/ui/__test__/__snapshots__/FormTitle.test.js.snap
Labels: review-codacy

#51 Feature/design hero section 47
  package-lock.json
  public/header.png
  public/hero.png
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/__test__/Header.test.js
  src/components/__test__/__snapshots__/Footer.test.js.snap
  src/components/__test__/__snapshots__/Header.test.js.snap
  src/components/ui/Button.jsx
  src/components/ui/__test__/__snapshots__/Button.test.js.snap
  src/pages/index.jsx
Labels: fix-tests

#60 Feature/design thanks component 29
  package-lock.json
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Header.jsx
  src/components/PageIntro.jsx
  src/components/__test__/__snapshots__/Header.test.js.snap
  src/components/__test__/__snapshots__/TeamMember.test.js.snap
  src/components/ui/Button.jsx
  src/pages/index.jsx
  src/pages/thanks.jsx
  src/styles/globals.css
Labels: needs-detailed-design, UX

#55 Feature/design multiple choices button
  .github/pull_request_template.md
  .github/workflows/lint.yml
  package-lock.json
  src/components/Stepper.jsx
  src/components/stories/Stepper.stories.jsx
  src/components/ui/Button.jsx
  src/components/ui/radiogroup/RadioGroup.jsx
  src/components/ui/radiogroup/RadioGroup.test.js
  src/components/ui/radiogroup/RadioInputItem.jsx
  src/components/ui/radiogroup/RadioInputItem.test.js
  src/components/ui/radiogroup/__snapshots__/RadioGroup.test.js.snap
  src/components/ui/radiogroup/__snapshots__/RadioInputItem.test.js.snap
  src/components/ui/textarea/Textarea.jsx
  src/components/ui/textarea/Textarea.stories.jsx
  src/components/ui/textarea/__snapshots__/Textarea.test.js.snap
  src/pages/index.jsx
  src/styles/tailwind.css
Labels: UX

#68 feat: add radio group stories
  src/components/ui/radiogroup/RadioGroup.stories.jsx
Labels: enhancement
