Repository 202212-GIZ-YE-FEW/iDev, pull requests merged in 2023-05, with the labels that each got.

#144 Feature/build edit profile with its functionality 133
  public/locales/ar/profile.json
  public/locales/ar/signup.json
  public/locales/ar/validation.json
  public/locales/en/profile.json
  public/locales/en/signup.json
  public/locales/en/validation.json
  src/components/Navbar.jsx
  src/components/context/AuthContext.jsx
  src/components/ui/PreviewProfile.jsx
  src/components/ui/Select.jsx
  src/components/ui/__test__/__snapshots__/Login.test.js.snap
  src/components/ui/__test__/__snapshots__/Select.test.js.snap
  src/firebase/addData.js
  src/firebase/setData.js
  src/firebase/updateSubCollection.js
  src/pages/editprofile.jsx
  src/pages/login.jsx
  src/pages/signup.jsx
  src/pages/therapist.jsx
  src/utils/validationSchemaProfile.js
Labels: enhancement, refactor, security, authentication, feature, api

#166 Build and implement the payment api functionality
  package-lock.json
  package.json
  public/images/403.svg
  public/locales/ar/common.json
  public/locales/ar/payment.json
  public/locales/en/common.json
  public/locales/en/payment.json
  src/components/NoContent.jsx
  src/components/NotPermitted.jsx
  src/components/Payment/AddNewCardForm.jsx
  src/components/__test__/__snapshots__/Navbar.test.js.snap
  src/components/__test__/__snapshots__/TeamMember.test.js.snap
  src/components/ui/Input.jsx
  src/components/ui/Select.jsx
  src/layout/Layout.jsx
  src/pages/404.jsx
  src/pages/_app.jsx
  src/pages/payment-methods/add-new-card.jsx
  src/pages/payment-methods/index.jsx
  src/pages/signup.jsx
  src/pages/thanks.jsx
  src/utils/country.js
  tailwind.config.js
Labels: authentication, api

#155 design and development the blog page with images
  package-lock.json
  package.json
  public/locales/ar/blog.json
  public/locales/en/blog.json
  src/components/BlogCard.jsx
  src/components/__test__/__snapshots__/Footer.test.js.snap
  src/components/__test__/__snapshots__/Navbar.test.js.snap
  src/pages/blogs/index.jsx
  src/utils/constants.jsx
Labels: UI/UX, feature, api

#168 Featuer/enhance-editprofile-page-functionality-167
  package-lock.json
  package.json
  public/locales/ar/profile.json
  public/locales/ar/signup.json
  public/locales/en/profile.json
  public/locales/en/signup.json
  src/components/Navbar.jsx
  src/components/context/AuthContext.jsx
  src/components/ui/Input.jsx
  src/components/ui/PreviewProfile.jsx
  src/components/ui/Select.jsx
  src/components/ui/__test__/__snapshots__/Select.test.js.snap
  src/components/ui/__test__/__snapshots__/Signup.test.js.snap
  src/components/ui/__test__/__snapshots__/Therapist.test.js.snap
  src/firebase/updateSubCollection.js
  src/pages/_app.jsx
  src/pages/editprofile.jsx
  src/pages/login.jsx
  src/pages/signup.jsx
  src/pages/therapist.jsx
  src/styles/toastr.css
  src/utils/validationSchemaProfile.js
  tailwind.config.js
Labels: enhancement, fix-tests, minor

#177 Hotfix/fix navbar 176
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Dropdown.jsx
  src/components/Homepage/HeroSection.jsx
  src/components/Homepage/__test__/__snapshots__/HeroSection.test.js.snap
  src/components/Navbar.jsx
  src/components/__test__/Dropdown.test.js
  src/components/__test__/__snapshots__/Dropdown.test.js.snap
  src/components/__test__/__snapshots__/Footer.test.js.snap
  src/components/__test__/__snapshots__/HomePage.test.js.snap
  src/components/__test__/__snapshots__/Navbar.test.js.snap
  src/pages/careers.jsx
  src/utils/constants.jsx
Labels: 🪲bug, enhancement

#182 Feature/enhance booking appointment 169
  public/locales/ar/appointment.json
  public/locales/ar/common.json
  public/locales/ar/contact_us.json
  public/locales/ar/payment.json
  public/locales/en/appointment.json
  public/locales/en/common.json
  public/locales/en/payment.json
  src/components/BookAppointment.jsx
  src/components/Dropdown.jsx
  src/components/Homepage/HeroSection.jsx
  src/components/Homepage/TicketItem.jsx
  src/components/Homepage/TicketSection.jsx
  src/components/Homepage/__test__/__snapshots__/HeroSection.test.js.snap
  src/components/Homepage/__test__/__snapshots__/TicketItem.test.js.snap
  src/components/Navbar.jsx
  src/components/RequirementsSection.jsx
  src/components/Stepper.jsx
  src/components/__test__/__snapshots__/Dropdown.test.js.snap
  src/components/__test__/__snapshots__/Footer.test.js.snap
  src/components/__test__/__snapshots__/HomePage.test.js.snap
  src/components/__test__/__snapshots__/Navbar.test.js.snap
  src/components/context/AuthContext.jsx
  src/components/ui/Input.jsx
  src/config/nodemailer.js
  src/firebase/addData.js
  src/firebase/getDataField.js
  src/firebase/setData.js
  src/pages/api/appointments.js
  src/pages/api/contact.js
  src/pages/api/payment.js
  src/pages/appointment.jsx
  src/pages/blogs/[id].jsx
  src/pages/blogs/index.jsx
  src/pages/contact-us.jsx
  src/pages/editprofile.jsx
  src/pages/index.jsx
  src/pages/payment/index.jsx
  src/pages/requirements.jsx
  src/pages/signup.jsx
  src/utils/constants.jsx
Labels: enhancement, api

#185 fix(Google signing error)
  src/components/context/AuthContext.jsx
Labels: hotfix

#183 Redesign Edit Profile
  src/pages/editprofile.jsx
Labels: UI/UX

#189 fix(fix team page responsive)
  public/locales/ar/common.json
  public/locales/ar/payment.json
  public/locales/ar/success.json
  public/locales/en/common.json
  public/locales/en/payment.json
  public/locales/en/signup.json
  public/locales/en/success.json
  public/payment.png
  public/team/Abrar.jpg
  public/team/dhiashalabi.png
  public/team/haneenabdulglil.jpg
  public/team/jehad.png
  public/team/mohammedaljaberi.jpg
  public/team/mohbassura.jpg
  src/components/AddBlog.jsx
  src/components/CareerPhilosophy.jsx
  src/components/CreateVacancy.jsx
  src/components/Navbar.jsx
  src/components/TeamMember.jsx
  src/components/__test__/__snapshots__/Navbar.test.js.snap
  src/components/__test__/__snapshots__/TeamMember.test.js.snap
  src/pages/404.jsx
  src/pages/about.jsx
  src/pages/blogs/[id].jsx
  src/pages/blogs/index.jsx
  src/pages/careers/create.jsx
  src/pages/careers/index.jsx
  src/pages/index.jsx
  src/pages/login.jsx
  src/pages/payment/index.jsx
  src/pages/signup.jsx
  src/pages/success.jsx
  src/pages/team.jsx
Labels: UI/UX, hotfix

#191 feat: upgrade app packages
  package-lock.json
  package.json
  src/components/BookAppointment/__test__/__snapshots__/CounselingType.test.js.snap
  src/components/BookAppointment/__test__/__snapshots__/Issues.test.js.snap
  src/components/BookAppointment/__test__/__snapshots__/RelationshipStatus.test.js.snap
  src/components/BookAppointment/__test__/__snapshots__/SpecificQualities.test.js.snap
  src/components/BookAppointment/__test__/__snapshots__/TherapyBefore.test.js.snap
  src/components/Dropdown.jsx
  src/components/Homepage/__test__/__snapshots__/CommunicateThroughItem.test.js.snap
  src/components/Homepage/__test__/__snapshots__/CommunicateThroughSection.test.js.snap
  src/components/Homepage/__test__/__snapshots__/HeroSection.test.js.snap
  src/components/Homepage/__test__/__snapshots__/TrustTherapistSection.test.js.snap
  src/components/__test__/__snapshots__/BlogItem.test.js.snap
  src/components/__test__/__snapshots__/BlogsSection.test.js.snap
  src/components/__test__/__snapshots__/ChatItem.test.js.snap
  src/components/__test__/__snapshots__/HomePage.test.js.snap
  src/components/__test__/__snapshots__/Navbar.test.js.snap
  src/components/__test__/__snapshots__/TeamMember.test.js.snap
  src/components/ui/__test__/__snapshots__/Login.test.js.snap
  src/components/ui/__test__/__snapshots__/PreviewProfile.test.jsx.snap
  src/components/ui/__test__/__snapshots__/Signup.test.js.snap
Labels: config
